### ISSUE TITLE
Decide on how the request app will receive the patronID

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/stacks-service#36]
### Request `patronId` from cognito on client

When authorising on the client to get the `id_token` used to authenticate against Cognito and API gateway, we request the `patronId` then.

This will then be encoded in the  `authorization` header and the application will be able to decode it as a JWT.

- client
- login with patronID in scope
- get id_token JWT with patronID encoded
- send id_token as authorization header
- decode patronID in app`

**Comment by kenoir** [comment]
API Gateway passes us the patronId as it is an attribute on the cognito user.
